arturs_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("accounts/", include("django.contrib.auth.urls")),
]

todo/urls.py
from django.urls import path
from .views import (TagListView,
                    TaskListView,
                    TagCreateView,
                    TagDeleteView,
                    TaskCreateView,
                    TaskDeleteView,
                    complete_task,
                    TaskUpdateView,
                    TagUpdateView,)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("admin/", TaskListView.as_view(), name="admin"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("<int:pk>/status/", complete_task, name="task-status")
]

app_name = "todo"

todo/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    optional_deadline = models.DateTimeField(blank=True, null=True)
    the_boolean = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

todo/forms.py
from django import forms
from todo.models import Tag, Task


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    optional_deadline = forms.DateTimeField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "yyyy-mm-dd hr:m"})
    )

    class Meta:
        model = Task
        fields = ("content", "optional_deadline", "tags",)

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Tag, Task
from todo.forms import TagForm, TaskForm


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task
    form_class = TaskForm
    template_name = "todo/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


def complete_task(request, pk):
    task = Task.objects.get(id=pk)
    if task.the_boolean:
        task.the_boolean = False
    else:
        task.the_boolean = True
    task.save()
    return redirect(reverse_lazy("todo:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul style="margin-top: 30px" class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}
{% block content %}
  <div style="margin-top: 30px; justify-content: space-around;">
  <a style="display: inline; float: right; margin-right: 10px" type="button" class="btn btn-primary" href="{% url "todo:task-create" %}">Add task</a>
  <h1 style="display: inline">TODO list</h1>

  <table class="table">
  <thead>
  {% for task in task_list %}
    <tr>
    <td>
      {% if task.the_boolean is False %}
        <a style="float: right" type="button" class="btn btn-success" href="{% url 'todo:task-status' pk=task.id%}">Complete</a>
      {% else %}
        <a style="float: right" type="button" class="btn btn-secondary" href="{% url 'todo:task-status' pk=task.id%}">Undo</a>
      {% endif %}
      <h4 style="display: inline">
        {{ task.content  }}
      </h4>
        {% if task.the_boolean %}
          <h6 style="display: inline; color: green">Done</h6>
          {% else %}
          <h6 style="display: inline; color: red">To be done</h6>
        {% endif %}
      <br>
      <h6 style="display: inline">
        Created: {{ task.datetime }}
      </h6>
      {% if task.optional_deadline %}
        <br>
        <h6 style="color: brown; display: inline">Dead-line: {{ task.optional_deadline }}</h6>
      {% endif %}
      <br>

      <h6  style="display: inline;color: gray">Tags:{% for tag in task.tags.all %} {{ tag }} {% endfor %} </h6>

      <a href="{% url 'todo:task-update' pk=task.pk%}">Update</a>
      <a href="{% url 'todo:task-delete' pk=task.pk%}">Delete</a>
    </td>
    </tr>
  {% endfor %}
  </thead>
  </table>
  </div>
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div style="margin-top: 30px; justify-content: space-around; ">
  <h1>Delete Tag?</h1>
  <p>
    <i>Are you sure you want to delete this tag: {{ tag.name }} ?</i>
  All tasks related to this tag will be deleted as well
  </p>

  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
  <br>
  <a style="{margin: 5px}" href="{% url 'todo:tag-list'%}" class="btn btn-secondary">Cancel</a>
  </div>
{% endblock %}

templates/todo/tag_form.html
{%  extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
  </form>

{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% block content %}
  <div style="margin-top: 30px; justify-content: space-around;">
  <a style="display: inline; float: right" type="button" class="btn btn-success" href="{% url 'todo:tag-create' %}">Add</a>
  <h1 style="margin-bottom: 5px; display: inline">Tag list</h1>
  <table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% for tag in tag_list %}
    <tr>
    <td>{{ tag.name }}</td>
    <td>
      <a class="btn btn-secondary" href="{% url 'todo:tag-update' pk=tag.pk%}">Update</a>
    </td>
    <td>
      <a class="btn btn-secondary" href="{% url 'todo:tag-delete' pk=tag.pk%}">Delete</a>
    </td>
    </tr>
  {% endfor %}
  </div>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div style="margin-top: 30px; justify-content: space-around; ">
  <h1>Delete Task?</h1>
  <p>
    <i>Are you sure you want to delete this task: {{ task.content }} ?</i>
  </p>

  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
  <br>
  <a style="{margin: 5px}" href="{% url 'todo:index'%}" class="btn btn-secondary">Cancel</a>
  </div>
{% endblock %}

templates/todo/task_form.html
{%  extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
  </form>

{% endblock %}